name: xv2
channels:
  - esri
  - conda-forge
  - defaults
dependencies:
  - arcgis=1.6.0
  - fiona=1.8.20
  - geopandas=0.10.2
  - loguru=0.5.3
  - numpy=1.21.4
  - opencv=4.5.3
  - pillow=8.3.2
  - pytest=6.2.5
  - pytorch=1.10.0
  - rasterio=1.2.10
  - scikit-image=0.18.3
  - torchvision=0.10.1
  - tqdm=4.62.3