FROM nvidia/cuda:12.2.2-base-ubuntu22.04

RUN apt-get update --fix-missing && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
    git \
    gcc \
    python3 \
    pip \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# COPY requirements.txt /tmp/

# RUN pip install -r /tmp/requirements.txt